#lang racket

(require "struct.rkt")
(defstruct tree height girth age leaf-shape leaf-color)
(define coconut (make-tree 'height 30 'leaf-shape 'frond 'age 5))
(tree.height coconut)
(tree.leaf-shape coconut)
(tree.girth coconut)
(set!tree.height coconut 40)
(set!tree.girth coconut 10)
(tree.leaf-shape coconut)
(tree.girth coconut)

(defstruct tree height girth age (leaf-shape 'frond) (leaf-color 'green))
(define palm (make-tree 'height 60))
(tree.height palm)
(tree.leaf-shape palm)
(define plantain (make-tree 'height 7 'leaf-shape 'sheet))
(tree.height plantain)
(tree.leaf-shape plantain)
(tree.leaf-color plantain)
